# Generated by Django 2.0.3 on 2019-05-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='ticket_type',
        ),
        migrations.DeleteModel(
            name='Customertype',
        ),
    ]
