# Generated by Django 2.0.3 on 2019-05-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190508_0150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cinima',
            new_name='Cinema',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='cinimaname',
            new_name='cinemaname',
        ),
    ]
