# Generated by Django 2.0.3 on 2019-05-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190513_0128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cinema',
            new_name='Cinima',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='cinemaname',
            new_name='cinimaname',
        ),
    ]
